
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '12.0'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'SwiftView_Example' do
  pod 'SwiftView', :path => '../'
  pod 'Masonry', '~>1.1.0'
  pod 'SVProgressHUD', '~>2.3.1'
end
